name: movizenv
channels:
  - conda-forge
  - anaconda
  - mordred-descriptor
  - defaults
dependencies:
  - python=3.9
  - pip=24.0
  - numpy=1.21.3
  - pandas=1.5.3
  - umap-learn=0.5.3
  - shap=0.41.0
  - scikit-learn-extra=0.2.0
  - hdbscan=0.8.28
  - lightgbm=3.3.2
  - rdkit=2022.3.5
  - optuna=3.0.2
  - tqdm=4.64.0
  - ipython=7.33.0
  - matplotlib=3.6.3
  - sklearn-genetic
  - ipykernel=6.16.0
  - scikit-learn=1.0.2
  - seaborn=0.11.2
  - pillow=9.4.0
  - mordred
  - pip:
    - cairosvg==2.7.0
    - exmol==3.0.3
    - mlxtend
    - openai
    - padelpy
